language: go
go:
  - 1.7.5
  - 1.8.3
os:
  - linux
  # remove osx, getting vm from travis is extremely slow
  # - osx
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
script:
  - test -z "$(go get -a)"
  - test -z "$(gofmt -l ./)"
  - test -z "$(go vet -v ./...)"
  - go test ./...
  - go build
# after_success:
#   # Publish as pre-release if it isn't a pull request
#   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then go get github.com/mitchellh/gox && go get github.com/tcnksm/ghr; fi'
#   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then gox -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}" && ghr --username $GITHUB_USERNAME --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/; fi'
